#!/usr/bin/python

import unittest
import httplib
import json
import os
import imp
import sys

tutor_find_db = imp.load_source('tutor_find_db', 'tutor_find_db')

def request(text):
   """Make a request to the database's HTTP server"""

   tutor_find_db.open_db()
   response = tutor_find_db.handle_request(json.dumps(text))
   tutor_find_db.close_db()

   try:
      return json.loads(response)
   except ValueError:
      print response
      raise

def review(user, subject, score, text):
   return request({
      'action':     'submit_review',
      'session_id': user['session_id'],
      'subject_id': subject['user_id'],
      'score':      score,
      'text':       text})

def favorite(user, subject, status):
   return request({
      'action':     'set_favorite',
      'session_id': user['session_id'],
      'subject_id': subject['user_id'],
      'favorited':  status})

def update_user(user, name, tags):
   return request({
      'action':       'update_user',
      'name':         name,
      'subject_tags': tags,
      'session_id':   user['session_id']})

if os.access('tutor.db', os.R_OK):
   os.remove('tutor.db')

alice = request({'action': 'register', 'email': 'alice@example.org', 'password': 'password'})
bob   = request({'action': 'register', 'email': 'bob@example.org', 'password': 'password'})
cindy = request({'action': 'register', 'email': 'cindy@example.org', 'password': 'password'})

review(alice, bob, 5.0, 'good')
review(bob, alice, 4.0, 'decent')
review(alice, cindy, 5.0, 'great')
review(bob, cindy, 0.0, 'awful')

favorite(alice, bob, True)
favorite(alice, cindy, True)

update_user(alice, 'Alice Example', 'math,calculus,math2013')
update_user(bob,   'Bob Example', 'math,physics,phys1302')
update_user(cindy, 'Cindy Someone', 'physics,english,eng3110,phys1302')
